version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
volumes:
  app-volume: